FORMAT: 1A
HOST: https://dashboard.hologram.io

# iLost Front-end API [WIP]

Our tracker consists of two main modes;

+ **short-range:** an external bluetooth transciever (estimote) that connects to the iLost tracker

+ **long-range:** hologram nova attached to the tracker allows for cellular data transfer and cellular triangualtion for location.


## Group Long-range

## Basic long-range Requests

The Hologram HTTP API is a REST-style interface for managing Hologram devices,
accounts, and cloud data, our tracker is built on the hologram architecture.

Hologram provides the long range location tracking of the iLost tracker.

To authenticate to the API, you must provide your API key as a query string parameter in each request.

**HOWEVER using Cloud-to-Device Messaging does not require an API key**

Please contact Hussein, Mariano or Thairan for API keys.

Request bodies can be provided in either JSON or form-urlencoded formats. In the reference examples below,
only the JSON versions are shown, and the `apikey` query string parameter is omitted for brevity.


### Basic Examples

**GET**

```
curl --verbose --request GET \
'https://dashboard.hologram.io/api/1/users/me?apikey=2rjpYZZNzFAoGxAgEP2SC6moL3emyB'
```

**POST with JSON body**

```
curl --verbose --request POST \
--header "Content-Type: application/json" \
--data '{"deviceid": 56668, "body": "Hello device!"}' \
'https://dashboard.hologram.io/api/1/sms/incoming?apikey=2rjpYZZNzFAoGxAgEP2SC6moL3emyB'
```

**POST with form-urlencoded body**

```
curl --verbose --request POST \
--header "Content-Type: application/x-form-urlencoded" \
--data 'deviceid=56668&body=Hello%20device!' \
'https://dashboard.hologram.io/api/1/sms/incoming?apikey=2rjpYZZNzFAoGxAgEP2SC6moL3emyB'
```

## Basic Responses

All API responses are returned as JSON objects with the following fields:

* `success` (boolean) - Indicates whether the request was successful.
* `data` (object or array) - Contains the requested data or information about
  the operation that was performed. Only present when `success` is true.
* `error` (string) - Information about why the request failed. Only present when
  `success` is false.

In addition to these body fields, the API uses standard HTTP status codes
to indicate success (200) and common errors (403 Forbidden, etc).

### Examples

**Success response**

```
{
  "success": true,
  "data": {
    "msgcount": 1
  }
}
```

**Error response**

```
{
  "success": false,
  "error": "Not logged in"
}
```


## SMS [/api/1/sms]

### Send SMS to a device [POST /api/1/sms/incoming]

There is no cost to send SMS messages to Hologram devices via API.

Please request Back-end team for **{deviceid}**

+ Request (application/json)
    + Attributes
        + deviceid: 1234 (number, required) - ID of the device to send to
        + fromnumber: `+1-312-555-1212` (string, optional) - Phone number to display as the sender. Optional.
        + body: Hello world! (string) - ASCII Text representation of the SMS body

+ Request With base64-encoded body (application/json)
    + Attributes
        + deviceid: 1234 (number, required) - ID of the device to send to
        + fromnumber: `+1-312-555-1212` (string, optional) - Phone number to display as the sender. Optional.
        + base64body: SGVsbG8sIFdvcmxkIQo= (string) - Base64-encoded message body

+ Response 200 (application/json)
    + Attributes
        + success: true (boolean) - Was the request successful?

## Cloud-to-Device Messaging [/api/1/devices/message]

Send a TCP or UDP message to one or more devices on the Hologram network.
See the [guide](/docs/guide/cloud/message-to-device/) for details.

### Send message to a device [POST /api/1/devices/messages]

This method requires the API key (Send message to a device via webhook) is the reccomended path

+ Request (application/json)
    + Attributes
        + deviceids (array, required) - IDs of devices to send message
            + 1234 (number)
            + 1236 (number)
        + protocol: TCP (string, required) - The protocol to use: 'TCP' or 'UDP'
        + port: 80 (number, required) - The port to use
        + data: Hello world! (string) - The data to send. Max length of 10k bytes. Must send either data or base64data
        + base64data: SGVsbG8gd29ybGQhCg== (string) - The data to send, encoded in base64. Max length of 10k bytes. Must send either data or base64data
+ Response 200 (application/json)
    + Attributes
        + success: true (boolean) - Was the request successful?
        + data (array)
            + (object)
                + deviceid: 1234 (number)
                + messageid: 9a9e55f0-a167-4d9d-972e-b2ad0740d449 (string)

### Send message to a device via webhook [POST /api/1/devices/messages/{deviceid}/{webhookguid}]

**HIGHLY RECCOMENDED** 

This endpoint does not require authentication with your API key, as the webhook GUID serves as
an authentication token.

Please request Back-end team for;

+ **{deviceid}**

+ **{webhookguid}**


+ Parameters
    + deviceid: 12345 (number) - ID of the device to send to
    + webhookguid: f56839c23a801251af8bf8c820f28a1f (string) - generated UUID for the webhook URL

+ Request (application/json)
    + Attributes
        + data: Hello world! (string) - The data to send. Max length of 10k bytes. Must send either data or base64data
        + base64data: SGVsbG8gd29ybGQhCg== (string) - The data to send, encoded in base64. Max length of 10k bytes. Must send either data or base64data
+ Response 200 (application/json)
+ Attributes
    + success: true (boolean) - Was the request successful?
    + data (array)
        + (object)
            + deviceid: 1234 (number)
            + messageid: 9a9e55f0-a167-4d9d-972e-b2ad0740d449 (string)


## Data Structures

### User (object)

+ id: 1234 (number) - Unique user id
+ email: joe@example.com (string, required) - Email address of user.
    This is the address that is used for logging into the Hologram Dashboard.
+ partnerid: 123 (number)ds
+ first: Joe (string) - First name
+ last: Schmoe (string) - Last name
+ role (string) - Indicates if the user is an admin. Normally empty.
+ registered (string) - Date that the user created her account
    + Sample: 2015-05-30 20:41:28
+ billingmethod (string)

### Organization (object)

+ id: 2345 (number) - Unique ID for the organization
+ name: Smart Things LLC (string) - Display name
+ is_personal: false (boolean) - Is this organization a personal organization belonging to a single user?
+ ownerid: 1234 (number) - ID of the user that created the organization
+ users (array) - Members of the organization
+ pending (array) - Users with pending invitations to the organization

### OrgUser (object)

+ id: 1234 (number) - Unique user id
+ email: joe@example.com (string) - Email address of user.
+ first: Joe (string) - First name
+ last: Schmoe (string) - Last name
+ permissions (array) - Which actions the user has permission to perform
    + billing
    + activation
    + changeplan

### Account Balance (object)

+ userid: 1234 (number)
+ orgid: 2345 (number) - Organization ID
+ balance: 96.05 (string) - User balance
+ promobalance: 0.00 (string) - Additional balance from promotions
+ minbalance: 50.00 (string) - Auto reload minimum balance as configured in the dashboard
+ topoffamount: 0.00 (string) - Auto reload amount as configured in the dashboard
+ pendingcharges: 0 (string)

### Order Data (object)

+ preview: false (boolean) - Was the request a preview (true) or an actual transaction (false)?
+ sku: ACCTREFILL (string)
+ unit_cost: 123.50 (number)
+ total_cost: 123.50 (number)
+ description: Refill Account Balance (string)
+ extra_description: User purchased account refill (string)
+ needs_shipping: false (boolean)
+ shipping_cost: 0 (number)

### Cellular Link (object)

+ id: 4321 (number) - The link's unique integer ID
+ deviceid: 1234 (number) - Device ID corresponding to the link
+ devicename: "My Device" (string) - Description of the device
+ orgid: 123 (number) - ID of the organization that owns the link
+ tunnelable: 0 (number) - Is tunneling enabled for the link? (1=true, 0=false)
+ partnerid (number)
+ sim: 9990000000000001234 (string) - SIM number corresponding to the link
+ msisdn: 999900001234 (string) - MSISDN corresponding to the link
+ imsi: 123456789876543 (number) - IMSI corresponding to the link
+ dataplansubscriptionid: 75 (number) - The link's data plan type
+ tier: 1 (number) - Geographical zone of the link's data plan
+ carrier: 2 (number) - ID of the carrier that the link last connected to
+ state: LIVE (string) - State of the link (LIVE, PAUSE, DEACTIVATE)
+ whenclaimed (string) - Timestamp when the SIM was activated
    + Sample: 2016-10-17 15:56:16
+ whenexpires (string) - Timestamp when the current billing period ends, or when the subscription expired
    + Sample: 2017-01-15 15:59:53
+ whencreated (string) - Timestamp when the link's record was first created
    + Sample: 2016-10-04 04:57:17
+ overagelimit: 20000 (number) -
    Configured overage limit, or -1 if no limit is set. See the
    [guide](https://hologram.io/docs/guide/connect/device-management#data-and-overage-limits)
    for details on overage limits.
+ apn: hologram (string) - APN to use when connecting with this link's SIM card

### Data Plan (object)

+ id: 127 (number) - Unique integer ID for the data plan
+ partnerid: 1 (number) - unused
+ name: 1 MB (string) - Human-readable name
+ description (string)
+ data: 1000000 (number) - Monthly data included in the plan (in bytes)
+ recurring: 1 (number) - for internal use
+ enabled: 1 (number) - Whether plan is available for new subscriptions
+ amount1: 0.99 (string) - Monthly base cost (zone 1)
+ amount2: 1.29 (string) - Monthly base cost (zone 2)
+ amount3 (string) - Monthly base cost (zone 3, unused)
    + Sample: -1.00
+ amount4 (string) - Monthly base cost (zone 4, unused)
    + Sample: -1.00
+ amount5 (string) - Monthly base cost (zone 5, unused)
    + Sample: -1.00
+ billingperiod: 1 - for internal use
+ overage1: 1.00 (string) - Data overage cost per MB (zone 1)
+ overage2: 1.50 (string) - Data overage cost per MB (zone 2)
+ overage3 (string) - Data overage cost per MB (zone 3, unused)
    + Sample: -1.00
+ overage4 (string) - Data overage cost per MB (zone 4, unused)
    + Sample: -1.00
+ overage5 (string) - Data overage cost per MB (zone 5, unused)
    + Sample: -1.00
+ sms1: 0.19 (string) - Outbound SMS cost per message (zone 1)
+ sms2: 0.30 (string) - Outbound SMS cost per message (zone 2)
+ sms3 (string) - Outbound SMS cost per message (zone 3, unused)
    + Sample: -1.00
+ sms4 (string) - Outbound SMS cost per message (zone 4, unused)
    + Sample: -1.00
+ sms5 (string) - Outbound SMS cost per message (zone 5, unused)
    + Sample: -1.00
+ trialdays: 0 (string) - for internal use
+ templateid: 0 (string) - for internal use
+ carrierid: 2 (number) - for internal use
+ groupid: 0 (number) - for internal use

### Device Tag (object)

+ name: My Tag (string) - Human-readable tag name
+ id: 123 (number) - Unique integer ID
+ deviceids (array) - IDs of devices linked to this tag
    + 1234 (number)
    + 1236 (number)

### Device (object)

+ id: 1234 (number) - Integer device ID
+ orgid: 321 (number) - ID of the organization that owns the device (may be a personal organization)
+ name: My Device (string) - User-configurable device name
+ type (string) - for internal use
+ whencreated (string) - Timestamp when the device record was created
+ phonenumber (string) - Device phone number, if configured
+ tunnelable: 0 (number) - Is tunneling enabled for the device?
    See the [guide](https://hologram.io/docs/guide/cloud/spacebridge-tunnel) for details
+ hidden: 0 (number) - for internal use
+ tags (array) - Configurable device categories. See [Device Tags](#reference/device-management/device-tags/) for details.
+ links
    + cellular (array) - Information about the device's SIM and data plan

### Tunnel Key (object)

+ id: 1234 (number) - Integer key ID
+ userid: 4321 (number) - ID of the user that the key belongs to
+ disabled: 0 (number) - Non-zero if the key is disabled
+ public_key: `ssh-rsa AAAAB3Nzaasdf... user@example.com` (string) - Public key


## Group Short-range

### Basic short-range Requests

[WIP] were focusing on getting long range to work first